### PR TITLE
Upgrade dependencies; change logging to Log4j2

### PR DESCRIPTION
**Pull request by artembilan**

### CODE REVIEW

**Comment by artembilan** [comment]
Hm. I made this PR for some reasons. and looks like long time ago.

Let me know if it makes sense to up-to-date it!
Or let's just close it as no value otherwise!

Thanks

**Comment by garyrussell** [comment]
Hmmm - missed this somehow; looks like it makes sense, if you want to rebase and fix up versions.

**Comment by artembilan** [comment]
OK. I have just pushed some clean ups after rebase onto `master`.

Thanks

**Comment by garyrussell** [comment]
Why did you remove junit?

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.281 s
[INFO] Finished at: 2019-12-03T09:31:58-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile (default-testCompile) on project spring-rabbit-stocks: Compilation failure: Compilation failure: 
[ERROR] /Users/grussell/Development/spring-amqp-samples/stocks/src/test/java/org/springframework/amqp/rabbit/stocks/Server.java:[19,16] error: package org.junit does not exist
...
```

**Comment by artembilan** [comment]
I just forgot that `junit` is now `optional` on `spring-rabbit-test`

**Pull request merged**
