### PR TITLE
Tutorials Refactor

### PR DESCRIPTION
**Pull request by sdeeg-pivotal**
This is a refactor of the original tutorials submitted by Gary.  It flattens the original package structure, and uses spring profiles to control it's behavior.  Each tutorial is now 3 classes with all bean creation in a Config class and sender/receiver logic in their own classes.  I preserved the explicit shutdown of the sender threads by wrapping them in a Lifecycle bean, but externalized it from how Gary did it.  Did a major rewrite of README.md.

### CODE REVIEW

**Comment by artembilan** [comment]
Hello, @sdeeg-pivotal !

Thank you very much for your hard work! :smile: 

@garyrussell said me that you are very busy guy, so let me just show you a polishing from my side, but not the whole complex review process on your code.
It is here https://github.com/artembilan/spring-amqp-samples/commit/24f7a561a3c254460fa1874301680b8566d1406d.

The most important thing is `ClientEmulator` instead of your `SpringAwareExecutorWrapper`. Because it doesn't work properly and we end up with:
> Exception in thread "pool-4-thread-1" java.lang.IllegalStateException: The ApplicationContext is closed and the ConnectionFactory can no longer create connections.
	at org.springframework.util.Assert.state(Assert.java:392)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:496)
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$1.createConnection(ConnectionFactoryUtils.java:80)
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:130)
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:67)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1278)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1271)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.send(RabbitTemplate.java:619)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(RabbitTemplate.java:687)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(RabbitTemplate.java:683)
	at org.springframework.amqp.tutorials.tut4.Tut4Sender.run(Tut4Sender.java:51)

Such a noise is scaring people, who studies the Framework using samples.
Right, I have the same issue there, but the tricky `@EventListener` helps me to overcome it.

Hope I'm not so strict with the code refactoring there, but in most cases it's just an automatic tool from the IDE according to the Spring Framework code style settings.

Looking forward for more contributions!

**Comment by sdeeg-pivotal** [comment]
Hi @artembilan - thank you so much for taking the time to review my PR.  This is my first one, and I'm still figuring it out, so please forgive my basic questions, but what are the next steps in the process?

What I think is that I want to grab the code from your fork, review/update/extend, then push to my branch.  When I eventually get my branch clean enough, then you will accept it into the main repo.  Is this basically correct?

What is the best way to get the code from your fork?  Should I reset the upstream on my local copy and pull?  Clone your fork and copy to my branch?

**Comment by artembilan** [comment]
Hello, @sdeeg-pivotal !

M-m-m. From big height no: you don't need to do anything.
Everything else is just our with @garyrussell routine :smile: .

Your first PR is very cool, strait-forward and even from Gary's perspective that was enough to merge as is.

To make my changes locally (just to play, of course) you should add me to your Git `remotes`. `fetch --all` than `pull artembilan tutorials` to the same your local branch.
We usually share polishing to each other for better review before merging to master.
So, if you'd like you can take a look there and leave your thoughts.

Thank you one more time for the contribution and feel free to come with more!

**Comment by sdeeg-pivotal** [comment]
@artembilan I'm interested in understanding your use of the flag to control if the task if run or not.  Is there a possibility that thread scheduler which calls the runTask method would fire after the context is closed and the ContextClosedEvent triggers the contextClosed method?  I would have thought that when the context is closed there would be no more scheduled tasks (and threads running scheduled tasks would be cleaned up).

If this is the case then the ClientEmulator could be eliminated altogether, and the sender objects would add the @Scheduled annotation to their method that sends messages.

**Comment by artembilan** [comment]
Cool, @sdeeg-pivotal !
Will review it over weekend.

Thank you for the contribution one more time!

**Comment by artembilan** [comment]
@sdeeg-pivotal ,

merged as https://github.com/spring-projects/spring-amqp-samples/commit/06baf7b6bb8742fd14b8cd09f07246ac8d14ed19.

Note that I've moved `@EnableScheduling` to the `@SpringBootApplication` - no reason to introduce one more `@Configuration` just for the annotation.

From other side I've made this sample based on the Spring AMQP-1.5.3. See https://jira.spring.io/browse/AMQP-546 for more info.
I really observe similar issue with previous version.

Thank you one more time!
And you are welcome for more!

**Pull request closed without merging**
